config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bookings#index"
  resources :books
  resources :users
  get 'bookings', to: 'bookings#index'
  get 'bookings/new', to: 'bookings#new'
  post 'bookings', to: 'bookings#create'
  get 'bookings/:id/edit' , to: 'bookings#edit'
  put 'bookings/:id' , to: 'bookings#update'
  delete 'bookings/:id', to: 'bookings#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :bookings
    has_many :users, through: :bookings
    validates :name, :author, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :book
    belongs_to :user
    validates :start_date, :end_date, presence: true
    validate :date_validation

    private
    def date_validation
        return if end_date.blank? || start_date.blank?

        if end_date < start_date
            errors.add(:end_date, notice: "Debe ser posterior a la fecha de inicio") 
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
    has_many :bookings
    has_many :books, through: :bookings
    validates :name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
    def require_admin
        unless current_user && current_user.role == 'Admin'
          redirect_to new_user_session_path
        end
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def index
        @bookings = Booking.all
    end

    def new
        @booking = Booking.new
        @books = Book.all
        @users = User.all
        if current_user && current_user.role == "Usuario"
            @user = current_user
        end
    end

    def create
        @booking = Booking.new(booking_params)
        if @booking.save
            redirect_to bookings_path, notice: "La reserva del libro se creó correctamente."
        else
            @books = Book.all
            @users = User.all
            if current_user && current_user.role == "Usuario"
                @user = current_user
            end
            render :new
        end
    end

    def edit
        @books = Book.all
        @users = User.all
        @booking = Booking.find(params[:id])
    end

    def update
        @booking = Booking.find(params[:id])
        if @booking.update(booking_params)
            redirect_to bookings_path, notice: "La reserva del libro se actualizó correctamente."
        else
            @books = Book.all
            @users = User.all
            render :edit
        end
    end

    def destroy
        @booking = Booking.find(params[:id])
        if @booking.destroy
            redirect_to bookings_path, notice: "La reserva del libro se eliminó con éxito."
        end
    end

    private
    def booking_params
        params.require(:booking).permit(:book_id, :user_id, :start_date, :end_date)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "El libro se creó correctamente." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "El libro se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "El libro se eliminó con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :isbn, :author, :year_publication, :editorial, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_admin
  
  # GET /users or /users.json
  def index
    @users = User.all
 
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "El usuario se creó correctamente." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "El usuario se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "El usuario se eliminó con éxito." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :last_name, :phone, :email, :password ,:role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/edit.html.erb
<h1> Editando Reserva de Libro</h1>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br />
<br />
<%= form_for @booking, url:"/bookings/#{@booking.id}", method:'put' do |f| %>
    <%= f.label 'Libro'%>
    <%= f.select "book_id", options_from_collection_for_select(@books, "id", "name", @booking.book_id)%>
    <br />
    <br />
    <%= f.label 'Usuario' %>
    <%= f.select "user_id", options_from_collection_for_select(@users, "id", "name", @booking.user_id)%>
    <br />
    <br />
    <%= f.label 'Fecha de Inicio' %>
    <%= f.date_field :start_date %>
    <br />
    <br />
    <%= f.label 'Fecha de Fin' %>
    <%= f.date_field :end_date %>
    <br />
    <br />
    <%= f.submit 'Editar Reserva'%>
<% end %>
<br />
<button><a href='/bookings'> Volver a los libros reservados</a></button>
<br />

app/views/bookings/index.html.erb
<br />
<h1> Libros reservados </h1>

<table>
  <thead>
    <tr>
      <th>Libro</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Fecha Inicio reserva</th>
      <th>Fecha Fin reserva</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |b| %>
      <tr>
        <td><%= b.book.name %></td>
        <td><%= b.user.name %></td>
        <td><%= b.user.last_name %></td>
        <td><%= b.start_date.strftime("%d-%b-%Y") if b.start_date %></td>
        <td><%= b.end_date.strftime("%d-%b-%Y") if b.end_date %></td>
        <% if current_user && current_user.role == "Admin" %>
        <td><button class="button_style" style="background-color:#4e9af1"><%= link_to 'Editar', "bookings/#{b.id}/edit"%></button></td>
        <td><button class="button_style" style="background-color:#f14e4e"><%= link_to 'Eliminar', "bookings/#{b.id}", method: :delete, data: { confirm: 'Estas seguro?' } %></button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<br />
<button><a href='/bookings/new'> Crear nueva reserva de Libro</a></button>
<br />
<br />
<button><%= link_to 'Libros', books_path %></button>
<% if current_user && current_user.role == "Admin" %>
<br />
<br />
<button><%= link_to 'Usuarios', users_path %></button>
<% end %>
<br />

app/views/bookings/new.html.erb
<h1> Reservar Libro </h1>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
        <% @booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br />
<br />
<%= form_for @booking, url:'/bookings', method:'post' do |f| %>
    <%= f.label 'Libro'%>
    <%= f.select "book_id", options_from_collection_for_select(@books, "id", "name")%>
    <br />
    <br />
    <%= f.label 'Usuario' %>
    <% if current_user && current_user.role == "Admin" %>
    <%= f.select "user_id", options_from_collection_for_select(@users, "id", "name")%>
    <% else %>
    <%= f.select "user_id", options_from_collection_for_select([@user], "id", "name")%>
    <% end %>
    <br />
    <br />
    <%= f.label 'Fecha de Inicio' %>
    <%= f.date_field :start_date %>
    <br />
    <br />
    <%= f.label 'Fecha de Fin' %>
    <%= f.date_field :end_date %>
    <br />
    <br />
    <%= f.submit 'Crear reserva de libro'%>
<% end %>
<br />
<button><a href='/bookings'> Volver a los libros reservados</a></button>
<br />

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'Isbn' %>
    <%= form.number_field :isbn %>
  </div>

  <div class="field">
    <%= form.label 'Autor' %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label 'Año de publicación' %>
    <%= form.date_field :year_publication %>
  </div>

  <div class="field">
    <%= form.label 'Editorial' %>
    <%= form.text_field :editorial %>
  </div>

  <div class="field">
    <%= form.label 'Descripción' %>
    <%= form.text_area :description, style:"height: 150px; width: 221px;" %>
  </div>

  <div class="actions">
    <%= form.submit button%>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editando Libro</h1>

<%= render 'form', book: @book, button: "Actualizar Libro" %>

<button><%= link_to 'Ver', @book %></button>
<button><%= link_to 'Atrás', books_path %></button>
<br />

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<br />
<h1>Lista de Libros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Isbn</th>
      <th>Autor</th>
      <th>Año de publicación</th>
      <th>Editorial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.name %></td>
        <td><%= book.isbn %></td>
        <td><%= book.author %></td>
        <td><%= book.year_publication.strftime("%d-%b-%Y") if book.year_publication %></td>
        <td><%= book.editorial %></td>
        <td><button class="button_style" style="background-color:#4ef18f"><%= link_to 'Ver', book %></button></td>
        <% if current_user && current_user.role == "Admin" %>
        <td><button class="button_style" style="background-color:#4e9af1"><%= link_to 'Editar', edit_book_path(book) %></button></td>
        <td><button class="button_style" style="background-color:#f14e4e"><%= link_to 'Eliminar', book, method: :delete, data: { confirm: 'Estas seguro?' } %></button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<% if current_user && current_user.role == "Admin" %>
<button><%= link_to 'Agregar Nuevo Libro', new_book_path %></button>
<br />
<br />
<button><%= link_to 'Usuarios', users_path %></button>
<br />
<br />
<% end %>
<button><%= link_to 'Lista de Libros Reservados', bookings_path %></button>
<br />

app/views/books/new.html.erb
<h1>Nuevo Libro</h1>

<%= render 'form', book: @book ,button: "Crear Libro"%>

<button><%= link_to 'Atrás', books_path %></button>
<br />

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Año de publicación:</strong>
  <%= @book.year_publication.strftime("%d-%b-%Y") if @book.year_publication%>
</p>

<p>
  <strong>Editorial:</strong>
  <%= @book.editorial %>
</p>

<p class="description">
  <strong>Descripción:</strong>
  <%= @book.description %>
</p>

<% if current_user && current_user.role == "Admin" %>
<button><%= link_to 'Editar', edit_book_path(@book) %></button>
<% end %>

<button><%= link_to 'Atrás', books_path %></button>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectBiblio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style='text-align: center'>
    <h1>Proyect Biblio ISFDYT N° 210</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  <br>
  
    <% if current_user %>
      <button><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></button>
    <%end%>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'Apellido' %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label 'Telefeno' %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label 'Email' %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label 'Password' %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label 'Rol' %>
    <%= form.select(:role, options_for_select([ "Admin", "Usuario" ], user.role ? user.role : "Usuario")) %>
  </div>

  <div class="actions">
    <%= form.submit button%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editando Usuario</h1>

<%= render 'form', user: @user , button: "Actualizar Usuario"%>

<button><%= link_to 'Ver', @user %></button>
<button><%= link_to 'Atrás', users_path %></button>
<br />

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<br />
<h1> Lista de Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefeno</th>
      <th>Email</th>
      <th>Rol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><button class="button_style" style="background-color:#4ef18f"><%= link_to 'Ver', user %></button></td>
        <td><button class="button_style" style="background-color:#4e9af1"><%= link_to 'Editar', edit_user_path(user) %></button></td>
        <td><button class="button_style" style="background-color:#f14e4e"><%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Estas seguro?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />
<br />
<button><%= link_to 'Agregar Nuevo Usuario', new_user_path %></button>
<br />
<br />
<button><%= link_to 'Libros', books_path %></button>
<br />
<br />
<button><%= link_to 'Lista de Libros Reservados', bookings_path %></button>
<br />

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form', user: @user ,button: "Crear Usuario"%>

<button><%= link_to 'Atrás', users_path %></button>
<br />

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Telefeno:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @user.role %>
</p>

<button><%= link_to 'Editar', edit_user_path(@user) %></button>
<button><%= link_to 'Atrás', users_path %></button>
<br />